###############
#
# Configurations
###############


#Main info about server
#REQUIMENTS:
# - MySQL
# - Linux Bash (optional)

#Server ID & Name
ID: 1
Server: "Main"

#Database Connection Settings
MySql: false
#MySql Parameters
host: 0.0.0.0
port: 3306
user: root
password: xxxxxx
db: main_db

#Fake slots settings
#Max Fake slots
FakeMax: 50
#Update Interval, in SECONDS
FakeInterval: 40
