###############
#
# Configurations
###############


#Main info about server
#REQUIMENTS:
# - MySQL
# - Linux Bash (optional)

#Server ID & Name
ID: 1
Server: "Main"

#Database Connection
host: 0.0.0.0
port: 3306
user: root
password: xxxxxx
db: main_db
